### ISSUE TITLE
MSRV violation

### ISSUE THREAD

**Issue by Emoun** [eupn/macrotest#68]
`macrotest` no longer compiles on rust v1.34.2 because `serde_json` v1.0.73 depends on `itoa` v1.0.1 which doesn't compile on that version. See (duplicate build)[https://github.com/Emoun/duplicate/runs/4636793495?check_suite_focus=true].

As far as I can tell `serde_json` has no MSRV, which means `macrotest` should depend on a specific version to avoid violating MSRV.

**Comment by taiki-e** [comment]
I would suggest raising the MSRV of `macrotest` to 1.36 which is the MSRV of `serde_json`. This crate is a crate for testing and there doesn't seem to be much worth sticking around to support a very old compiler.
See also https://github.com/rust-lang/api-guidelines/pull/227#discussion_r527102913 and https://github.com/rust-lang/api-guidelines/pull/227/commits/38e610d13446dd81a09c81ec6121037706ee74d4:

> Some crate bumps MSRV of the crate itself due to MSRV bump of the dev-dependency, but in some cases, the crate itself can be compiled with an older version, even if the dev-dependency requires a newer version.
I'm not sure if it's really preferable to recommend `cargo test` instead of `cargo build` here.
AFAIK there are many projects that do not run `cargo test` on MSRV, but only run `cargo build`. (e.g., [serde](https://github.com/serde-rs/serde/blob/e3d871ff7bf10dadf10bdc234a55692228358d0e/.github/workflows/ci.yml#L63-L78), [syn](https://github.com/dtolnay/syn/blob/2c83686bede4f64353e9ad10033a23f77e56eb94/.github/workflows/ci.yml), [regex](https://github.com/rust-lang/regex/blob/3bcae3b6954ea3628ef0974f0a2604a6ae248408/.github/workflows/ci.yml#L99-L103), [tokio](https://github.com/tokio-rs/tokio/blob/479c545c20b2cb44a8f09600733adc8c8dcb5aa0/.github/workflows/ci.yml#L182), [futures](https://github.com/rust-lang/futures-rs/blob/master/.github/workflows/ci.yml), etc...)

> In practice, dev-deps often have much more lenient MSRV policy than then crate under test. Using `build` rather than `test` works around that.

---

> macrotest should depend on a specific version to avoid violating MSRV.

I think this is far worse than violating the MSRV because if other dependencies requires the recent version of serde_json, this causes compile error.

I think the right place to do this is in the end-user's Cargo.toml or Cargo.lock ([example](https://github.com/taiki-e/pin-project/blob/d076aedcc44fa7c353976c72980b514b6797df8f/Cargo.toml#L37-L39)).

---

> `serde_json` has no MSRV

No. serde_json v1.0.73's MSRV is Rust 1.36. See rust-version field in [serde-json's Cargo.toml](https://github.com/serde-rs/json/blob/95f67a09399d546d9ecadeb747a845a77ff309b2/Cargo.toml#L14).

**Comment by Emoun** [comment]
> if other dependencies requires the recent version of serde_json, this causes compile error

Doesn't cargo just compile it twice?

> serde_json v1.0.73's MSRV is Rust 1.36. See rust-version field in serde-json's Cargo.toml.

Thanks, i missed that. Though, does the project maintain the MSRV across versions?
Regardless, since `serde_json`'s MSRV is higher than `macrotest`'s, it seems to me fixing the version would be needed to comply with the current MSRV.

I'm not strictly against `macrotest` upping it's MSRV, I've been thinking about doing it for `duplicate`. However, I think it should be part of a major version bump.

**Comment by taiki-e** [comment]
> Doesn't cargo just compile it twice?

It will be compiled twice if the major versions (or minor versions if the major version is 0) are different. In other cases, it will be conflict and cause compile error. See https://github.com/smol-rs/async-process/pull/4 for a specific example.

> However, I think it should be part of a major version bump.

AFAIK, many cornerstone libraries (include serde_json) don't consider an MSRV increase as a breaking change.
[This comment](https://github.com/crossbeam-rs/crossbeam/pull/444#discussion_r343737057) by matklad is one of the explanations that I find particularly reasonable as to why such a policy should be adopted.

See also:

- https://github.com/rust-lang/api-guidelines/pull/227
- https://github.com/rust-lang/api-guidelines/discussions/231
- https://github.com/rust-lang/api-guidelines/discussions/123

**Comment by Emoun** [comment]
> AFAIK, many cornerstone libraries (include serde_json) don't consider an MSRV increase as a breaking change.
Yeah, my opinion is not mainstream sadly, and would therefore also fully respect if `macrotest` decides to only bump the minor version.
